# Generated by Django 4.1 on 2025-07-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coderg', models.IntegerField()),
                ('codusuario', models.IntegerField()),
                ('codlibro', models.IntegerField()),
                ('sexo', models.TextField()),
                ('autor', models.TextField()),
                ('Fsalida', models.TextField()),
                ('Fentrega', models.TextField()),
            ],
        ),
    ]
